services:
  mysql:
    image: mysql:8.0
    container_name: finance_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_2024
      - MYSQL_DATABASE=personal_finance_db
      - MYSQL_USER=finance_user
      - MYSQL_PASSWORD=secure_password_2024
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - finance_network

  redis:
    image: redis:7-alpine
    container_name: finance_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - finance_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: finance_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root_password_2024
    depends_on:
      - mysql
    networks:
      - finance_network

  php:
    image: php:8.2-apache
    container_name: finance_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local